/**
 * engine.js — Reads config.js and renders the full site.
 * ⚠️  Do NOT edit this file. Change config.js instead.
 */
(function () {
  "use strict";
  const C  = window.SITE_CONFIG;
  const T  = C.theme;
  const AC = C.access;

  /* ── tiny helpers ─────────────────────────────────────── */
  const $   = (id) => document.getElementById(id);
  const mk  = (tag, cls) => { const e = document.createElement(tag); if (cls) e.className = cls; return e; };
  const esc = (s) => String(s ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
  const safe = (s) => String(s ?? "");
  const playSound = (key) => {
    if (!T.soundEnabled || !C.sounds[key]) return;
    try { new Audio(C.sounds[key]).play(); } catch(e) {}
  };

  /* ── apply theme CSS vars ──────────────────────────────── */
  function applyTheme(t) {
    const r = document.documentElement.style;
    r.setProperty("--pink",     t.colorPink);
    r.setProperty("--rose",     t.colorRose);
    r.setProperty("--blush",    t.colorBlush);
    r.setProperty("--cream",    t.colorCream);
    r.setProperty("--mint",     t.colorMint);
    r.setProperty("--lavender", t.colorLavender);
    r.setProperty("--ink",      t.colorInk);
    r.setProperty("--muted",    t.colorMuted);

    document.body.dataset.anim = t.animationLevel;

    if (t.backgroundStyle === "solid") {
      document.body.style.background = t.backgroundSolid;
      document.body.classList.remove("bg-stars");
    } else if (t.backgroundStyle === "stars") {
      document.body.classList.add("bg-stars");
      document.body.style.background = "";
    } else {
      document.body.classList.remove("bg-stars");
      document.body.style.background = "";
    }

    let fl = $("dyn-fonts");
    if (!fl) { fl = mk("link"); fl.id = "dyn-fonts"; fl.rel = "stylesheet"; document.head.appendChild(fl); }
    const dp = t.fontDisplay.replace(/ /g,"+");
    const bp = t.fontBody.replace(/ /g,"+");
    fl.href = `https://fonts.googleapis.com/css2?family=${dp}&family=${bp}:wght@500;700&display=swap`;
    document.body.style.setProperty("--font-display", `"${t.fontDisplay}", monospace`);
    document.body.style.setProperty("--font-body",    `"${t.fontBody}", system-ui, sans-serif`);
  }

  /* ── lock helpers ──────────────────────────────────────── */
  function isLocked(page) {
    if (!page.lock) return false;
    if (page.lock === "master") return !window._masterUnlocked;
    if (page.lock === "timer" && page.lockUntil) return new Date() < new Date(page.lockUntil);
    return false;
  }

  function cdStr(target) {
    const ms = Math.max(new Date(target) - new Date(), 0);
    const s  = Math.floor(ms/1000);
    return `${Math.floor(s/86400)}d ${Math.floor((s%86400)/3600)}h ${Math.floor((s%3600)/60)}m ${s%60}s`;
  }

  function attachLockOverlay(sec, page) {
    if (sec.querySelector(".lock-overlay")) return;
    const ov = mk("div","lock-overlay");
    const by = page.lock === "timer"
      ? `in <span class="mini-cd" data-target="${esc(page.lockUntil)}">${cdStr(page.lockUntil)}</span>`
      : "only for the master";
    ov.innerHTML = `<div class="lock-inner"><div class="lock-icon">🔒</div>
      <p class="lock-msg">This section unlocks ${by}.</p></div>`;
    sec.style.position = "relative";
    sec.appendChild(ov);
    if (page.lock === "timer") {
      const span = ov.querySelector(".mini-cd");
      const iv = setInterval(() => {
        const ms = Math.max(new Date(page.lockUntil) - new Date(), 0);
        if (ms === 0) { span.textContent = "Unlocked! Reload to enter."; clearInterval(iv); return; }
        span.textContent = cdStr(page.lockUntil);
      }, 1000);
    }
  }

  /* ── navigation ───────────────────────────────────────── */
  let curIdx = 0;
  const vPages = () => C.pages.filter(p => p.visible);

  function showPage(idx) {
    const pages = vPages();
    if (idx < 0 || idx >= pages.length) return;
    curIdx = idx;
    document.querySelectorAll(".portal-page").forEach(p => { p.hidden = true; });
    const page = pages[idx];
    const sec  = $(page.id);
    if (!sec) return;
    sec.hidden = false;
    if (isLocked(page) && page.type !== "unlock") attachLockOverlay(sec, page);
    sec.scrollIntoView({ behavior: "smooth", block: "start" });
    playSound("next");
  }

  /* ── emoji burst ──────────────────────────────────────── */
  function burst() {
    if (T.animationLevel === "none") return;
    playSound("burst");
    const wrap = mk("div","smiley-burst");
    document.body.appendChild(wrap);
    const pool = ["😊","🥹","😍","✨","💖","😄","🥳","💕"];
    for (let i = 0; i < 42; i++) {
      const s = mk("span","smiley");
      const a = Math.random()*Math.PI*2, d = 120+Math.random()*360;
      s.textContent = pool[Math.floor(Math.random()*pool.length)];
      s.style.cssText = `--tx:${Math.cos(a)*d}px;--ty:${Math.sin(a)*d}px;--rot:${Math.random()*180-90}deg;left:${10+Math.random()*80}%;top:${15+Math.random()*70}%;animation-delay:${Math.random()*240}ms`;
      wrap.appendChild(s);
    }
    setTimeout(() => wrap.remove(), 2100);
  }

  /* ── glitch ───────────────────────────────────────────── */
  function glitch(cb) {
    if (T.animationLevel === "none") { cb(); return; }
    const g = $("glitch-overlay");
    g.classList.add("is-active");
    setTimeout(() => { g.classList.remove("is-active"); cb(); }, 2200);
  }

  /* ── nav buttons ──────────────────────────────────────── */
  function addNav(parent, page) {
    const pages = vPages();
    const idx   = pages.findIndex(p => p.id === page.id);
    const co    = page.content;
    if (!co.prevButton && !co.nextButton) return;
    const nav = mk("div","page-nav");
    if (co.prevButton && idx > 0) {
      const b = mk("button","portal-btn prev-btn"); b.textContent = safe(co.prevButton);
      b.addEventListener("click", () => showPage(idx-1)); nav.appendChild(b);
    }
    if (co.nextButton && idx < pages.length-1) {
      const b = mk("button","portal-btn next-btn"); b.textContent = safe(co.nextButton);
      b.addEventListener("click", () => showPage(idx+1)); nav.appendChild(b);
    }
    parent.appendChild(nav);
  }

  /* ══════════════════════════════════════════════════════════
     PAGE RENDERERS
  ══════════════════════════════════════════════════════════ */

  function renderUnlock(page, sec) {
    const co = page.content;
    sec.innerHTML = `
      <div class="sparkles" aria-hidden="true">
        <span style="--x:8%;--y:15%;--d:0s">&#10022;</span>
        <span style="--x:84%;--y:11%;--d:.35s">&#9825;</span>
        <span style="--x:18%;--y:76%;--d:.7s">&#10047;</span>
        <span style="--x:78%;--y:74%;--d:.2s">&#10023;</span>
        <span style="--x:52%;--y:8%;--d:.9s">&#9829;</span>
      </div>
      <div class="unlock-card">
        <p class="eyebrow">${esc(co.eyebrow)}</p>
        <h1>${esc(co.title)}</h1>
        <p class="subtitle">${esc(co.subtitle)}</p>
        <form class="access-form" id="accessForm" novalidate>
          <label for="accessCode">Access code</label>
          <div class="input-row">
            <input id="accessCode" type="password" autocomplete="off" placeholder="${esc(co.inputPlaceholder)}" />
            <button type="submit">${esc(co.buttonLabel)}</button>
          </div>
          <p class="form-error" id="formError" role="alert"></p>
        </form>
        <div class="loader-panel" id="loaderPanel" aria-live="polite">
          <div class="loader-copy">
            <span class="pixel-label">LOADING</span>
            <span id="loaderPct">0%</span>
          </div>
          <div class="loading-track"><div id="loadingFill" class="loading-fill"></div></div>
          <p class="loader-status" id="loaderStatus">${esc(co.loaderMessages[0])}</p>
        </div>
      </div>`;

    const form  = $("accessForm");
    const input = $("accessCode");
    const err   = $("formError");
    const panel = $("loaderPanel");
    const pct   = $("loaderPct");
    const stat  = $("loaderStatus");
    const fill  = $("loadingFill");
    const btn   = form.querySelector("button");
    const msgs  = co.loaderMessages;

    form.addEventListener("submit", (e) => {
      e.preventDefault();
      const val = input.value.trim();
      if (!val) { err.textContent = "Please enter a code first."; input.focus(); return; }
      const isMaster = val === AC.masterCode;
      const isUser   = val === AC.userCode;
      if (!isMaster && !isUser) {
        err.textContent = AC.wrongCodeMessage; input.value = ""; input.focus(); return;
      }
      if (isMaster) window._masterUnlocked = true;
      err.textContent = ""; btn.disabled = true; input.disabled = true;
      panel.classList.add("visible");
      let prog = 0;
      const iv = setInterval(() => {
        prog = Math.min(prog + Math.floor(Math.random()*13)+8, 100);
        fill.style.width = prog+"%"; pct.textContent = prog+"%";
        stat.textContent = msgs[Math.min(Math.floor(prog/28), msgs.length-1)];
        if (prog >= 100) {
          clearInterval(iv);
          stat.textContent = msgs[msgs.length-1];
          setTimeout(() => {
            sec.hidden = true;
            glitch(() => { playSound("unlock"); if (isMaster) openAdmin(); showPage(1); });
          }, 600);
        }
      }, 220);
    });
  }

  function renderVideo(page, sec) {
    const co = page.content;
    const inner = mk("div","section-inner");
    inner.innerHTML = `
      <p class="eyebrow">${esc(co.eyebrow)}</p>
      <h2>${esc(co.title)}</h2>
      <div class="video-frame">
        <video id="portalVideo" controls preload="metadata">
          <source src="${esc(co.videoSrc)}" type="video/mp4" />
        </video>
        <div class="video-placeholder">
          <span>${esc(co.videoPlaceholderTitle)}</span>
          <small>${esc(co.videoPlaceholderText)}</small>
        </div>
      </div>`;
    addNav(inner, page);
    sec.appendChild(inner);
    const obs = new IntersectionObserver(entries => {
      entries.forEach(en => { if (en.isIntersecting) $("portalVideo")?.play().catch(()=>{}); });
    }, { threshold: 0.5 });
    obs.observe(sec);
  }

  function renderText(page, sec) {
    const co = page.content;
    const inner = mk("div","section-inner narrow");
    inner.innerHTML = `
      <p class="eyebrow">${esc(co.eyebrow)}</p>
      <h2>${esc(co.title)}</h2>
      ${co.body ? `<p class="sec-body">${esc(co.body)}</p>` : ""}`;
    addNav(inner, page);
    sec.appendChild(inner);
  }

  function renderMessage(page, sec) {
    const co = page.content;
    const inner = mk("div","section-inner narrow");
    inner.innerHTML = `
      <p class="eyebrow">${esc(co.eyebrow)}</p>
      <h2>${esc(co.title)}</h2>
      ${co.body ? `<div class="sec-body msg-body">${safe(co.body).replace(/\n/g,"<br>")}</div>` : ""}`;
    addNav(inner, page);
    sec.appendChild(inner);
  }

  function renderGallery(page, sec) {
    const co = page.content;
    const inner = mk("div","section-inner");
    const photosHtml = co.photos.map(p =>
      `<article class="fragment-card">
        ${p.src
          ? `<img class="fragment-photo" src="${esc(p.src)}" alt="${esc(p.alt)}" loading="lazy"/>`
          : `<div class="photo-placeholder">${esc(p.alt)}</div>`}
        <p>${esc(p.caption)}</p>
       </article>`).join("");
    const choicesHtml = co.choices.map(c => `<button type="button" class="portal-btn">${esc(c)}</button>`).join("");
    inner.innerHTML = `
      <p class="eyebrow">${esc(co.eyebrow)}</p>
      <h2>${esc(co.title)}</h2>
      <div class="fragment-grid">${photosHtml}</div>
      <div class="question-box">
        <p class="q-feedback" id="qfb-${page.id}">${esc(co.question)}</p>
        <div class="response-row">${choicesHtml}</div>
      </div>`;
    addNav(inner, page);
    sec.appendChild(inner);
    inner.querySelectorAll(".response-row .portal-btn").forEach(b => {
      b.addEventListener("click", () => {
        inner.querySelectorAll(".response-row .portal-btn").forEach(x => x.classList.remove("is-selected"));
        b.classList.add("is-selected");
        $(`qfb-${page.id}`).textContent = `${b.textContent} selected ✨`;
        burst();
      });
    });
  }

  function renderCountdown(page, sec) {
    const co = page.content;
    const inner = mk("div","section-inner narrow");
    const folderHtml = co.folders.map(f =>
      `<article class="folder-card">
        <div class="folder-icon" aria-hidden="true"></div>
        <p>${esc(f.label)}</p>
       </article>`).join("");
    const pid = page.id;
    inner.innerHTML = `
      <p class="eyebrow">${esc(co.eyebrow)}</p>
      <h2>${esc(co.title)}</h2>
      <div class="countdown-panel" aria-live="polite">
        <p>${esc(co.countdownLabel)}</p>
        <div class="countdown-grid">
          <span><strong id="cd-d-${pid}">00</strong>Days</span>
          <span><strong id="cd-h-${pid}">00</strong>Hours</span>
          <span><strong id="cd-m-${pid}">00</strong>Minutes</span>
          <span><strong id="cd-s-${pid}">00</strong>Seconds</span>
        </div>
      </div>
      <div class="folder-grid">${folderHtml}</div>`;
    addNav(inner, page);
    sec.appendChild(inner);
    const target = new Date(co.countdownTarget);
    const tick = () => {
      const ms = Math.max(target - new Date(), 0);
      const ts = Math.floor(ms/1000);
      $(`cd-d-${pid}`).textContent = String(Math.floor(ts/86400)).padStart(2,"0");
      $(`cd-h-${pid}`).textContent = String(Math.floor((ts%86400)/3600)).padStart(2,"0");
      $(`cd-m-${pid}`).textContent = String(Math.floor((ts%3600)/60)).padStart(2,"0");
      $(`cd-s-${pid}`).textContent = String(ts%60).padStart(2,"0");
    };
    tick(); setInterval(tick, 1000);
  }

  /* ══════════════════════════════════════════════════════════
     BUILD SITE
  ══════════════════════════════════════════════════════════ */
  function buildSite() {
    const app = $("app");
    app.innerHTML = "";

    /* glitch overlay */
    const g = mk("div","glitch-overlay"); g.id = "glitch-overlay"; g.setAttribute("aria-hidden","true");
    const glitchTxt = C.pages.find(p=>p.type==="unlock")?.content?.glitchText || "ACCESS GRANTED";
    g.innerHTML = `<div class="glitch-text" data-text="${esc(glitchTxt)}">${esc(glitchTxt)}</div>`;
    app.appendChild(g);

    /* pages */
    C.pages.filter(p => p.visible).forEach((page, i) => {
      const sec = mk("section", `portal-page ${page.type}-page ${page.id === "page-unlock" ? "unlock-screen" : "story-section"}`);
      sec.id = page.id;
      sec.hidden = (i !== 0);
      app.appendChild(sec);
      switch(page.type) {
        case "unlock":    renderUnlock(page, sec);    break;
        case "video":     renderVideo(page, sec);     break;
        case "text":      renderText(page, sec);      break;
        case "message":   renderMessage(page, sec);   break;
        case "gallery":   renderGallery(page, sec);   break;
        case "countdown": renderCountdown(page, sec); break;
      }
    });
  }

  /* ══════════════════════════════════════════════════════════
     ADMIN PANEL
  ══════════════════════════════════════════════════════════ */
  function openAdmin() {
    if ($("admin-panel")) { $("admin-panel").hidden = false; return; }
    const panel = mk("div"); panel.id = "admin-panel";
    panel.innerHTML = `
      <div id="adm-handle">⚙️ Admin Panel <button id="adm-close" title="Close">✕</button></div>
      <div id="adm-body">
        <p class="adm-hint">Type a command → press <b>Enter</b> or click <b>Apply</b></p>
        <div class="adm-row">
          <input id="adm-cmd" type="text" placeholder='set title "New Title" on page-video' autocomplete="off"/>
          <button id="adm-go">Apply</button>
        </div>
        <div id="adm-fb"></div>
        <details open><summary>📋 All Commands</summary><div class="cmd-ref">
<b>Text content:</b><br>
<code>set title "text" on page-video</code><br>
<code>set eyebrow "text" on page-archive</code><br>
<code>set subtitle "text" on page-unlock</code><br>
<code>set body "text" on page-archive</code><br>
<code>set caption 2 "text" on page-fragments</code><br>
<code>set folder 1 "Name" on page-final</code><br>
<code>set question "text?" on page-fragments</code><br>
<br><b>Theme — colors:</b><br>
<code>set color rose #ff6699</code><br>
<code>set color ink #3a1f30</code><br>
<code>set color mint #aaffdd</code><br>
<br><b>Theme — fonts:</b><br>
<code>set font display "Pacifico"</code><br>
<code>set font body "Nunito"</code><br>
<br><b>Theme — background:</b><br>
<code>set background gradient</code><br>
<code>set background solid #ffe4f0</code><br>
<code>set background stars</code><br>
<br><b>Animations &amp; sound:</b><br>
<code>set animation full</code><br>
<code>set animation reduced</code><br>
<code>set animation none</code><br>
<code>set sound on</code>&nbsp;&nbsp;<code>set sound off</code><br>
<br><b>Pages — show / hide:</b><br>
<code>show page page-letter</code><br>
<code>hide page page-fragments</code><br>
<br><b>Pages — lock / unlock:</b><br>
<code>lock page page-fragments timer 2026-07-01T13:00:00+05:30</code><br>
<code>lock page page-fragments master</code><br>
<code>unlock page page-fragments</code><br>
<br><b>Access codes:</b><br>
<code>set usercode "newcode123"</code><br>
<code>set mastercode "newmaster"</code><br>
<br><b>Countdown date:</b><br>
<code>set countdown 2026-07-10T00:00:00+05:30 on page-final</code><br>
<br><b>Utility:</b><br>
<code>reload</code> &nbsp;— re-render site<br>
<code>export config</code> &nbsp;— download updated config.js
        </div></details>
        <details><summary>📄 Page IDs</summary><div class="cmd-ref">
<code>page-unlock</code> — Access gate<br>
<code>page-video</code> — Birthday video<br>
<code>page-archive</code> — Archive status<br>
<code>page-fragments</code> — Photo gallery<br>
<code>page-final</code> — Countdown<br>
<i>Add custom pages in config.js</i>
        </div></details>
      </div>`;
    document.body.appendChild(panel);
    $("adm-close").addEventListener("click", () => { panel.hidden = true; });
    $("adm-go").addEventListener("click", runCmd);
    $("adm-cmd").addEventListener("keydown", e => { if (e.key==="Enter") runCmd(); });
    makeDraggable(panel, $("adm-handle"));
  }

  function makeDraggable(el, handle) {
    handle.style.cursor = "grab";
    let ox=0, oy=0;
    handle.addEventListener("mousedown", e => {
      e.preventDefault(); ox = el.offsetLeft-e.clientX; oy = el.offsetTop-e.clientY;
      const mv = e2 => { el.style.left=(e2.clientX+ox)+"px"; el.style.top=(e2.clientY+oy)+"px"; };
      const up = () => { document.removeEventListener("mousemove",mv); document.removeEventListener("mouseup",up); };
      document.addEventListener("mousemove",mv); document.addEventListener("mouseup",up);
    });
  }

  function admFb(msg, ok=true) {
    const fb = $("adm-fb"); if (!fb) return;
    fb.textContent = msg; fb.style.color = ok ? "var(--mint)" : "#ff7eb3";
    setTimeout(() => { fb.textContent = ""; }, 4000);
  }

  /* ── command parser ──────────────────────────────────── */
  function runCmd() {
    const raw = ($("adm-cmd")?.value || "").trim();
    if (!raw) return;

    try {
      /* reload */
      if (raw.toLowerCase() === "reload") { buildSite(); admFb("Site re-rendered ✓"); return; }

      /* export config */
      if (raw.toLowerCase() === "export config") { exportConfig(); return; }

      /* set sound on/off */
      if (/^set sound (on|off)$/i.test(raw)) {
        T.soundEnabled = raw.toLowerCase().includes("on");
        admFb(`Sound ${T.soundEnabled?"on":"off"} ✓`); return;
      }

      /* set animation full/reduced/none */
      const animM = raw.match(/^set animation (full|reduced|none)$/i);
      if (animM) { T.animationLevel = animM[1].toLowerCase(); applyTheme(T); admFb(`Animation → ${animM[1]} ✓`); return; }

      /* set color <name> <hex> */
      const colM = raw.match(/^set color (\w+) (#[0-9a-fA-F]{3,6})$/i);
      if (colM) {
        const k = "color"+colM[1][0].toUpperCase()+colM[1].slice(1);
        if (!(k in T)) { admFb("Unknown color: "+colM[1], false); return; }
        T[k] = colM[2]; applyTheme(T); admFb(`${colM[1]} → ${colM[2]} ✓`); return;
      }

      /* set font display/body "Name" */
      const fontM = raw.match(/^set font (display|body) "([^"]+)"$/i);
      if (fontM) {
        if (fontM[1].toLowerCase()==="display") T.fontDisplay = fontM[2];
        else T.fontBody = fontM[2];
        applyTheme(T); admFb(`Font ${fontM[1]} → "${fontM[2]}" ✓`); return;
      }

      /* set background gradient|stars|solid [hex] */
      const bgM = raw.match(/^set background (gradient|stars|solid)(?: (#[0-9a-fA-F]{3,6}))?$/i);
      if (bgM) {
        T.backgroundStyle = bgM[1].toLowerCase();
        if (bgM[2]) T.backgroundSolid = bgM[2];
        applyTheme(T); admFb(`Background → ${bgM[1]} ✓`); return;
      }

      /* set usercode / mastercode */
      const ucM = raw.match(/^set usercode "([^"]+)"$/i);
      if (ucM) { AC.userCode = ucM[1]; admFb(`User code → "${ucM[1]}" ✓`); return; }
      const mcM = raw.match(/^set mastercode "([^"]+)"$/i);
      if (mcM) { AC.masterCode = mcM[1]; admFb(`Master code → "${mcM[1]}" ✓`); return; }

      /* show/hide page */
      const shM = raw.match(/^(show|hide) page ([\w-]+)$/i);
      if (shM) {
        const pg = C.pages.find(p=>p.id===shM[2]);
        if (!pg) { admFb("Page not found: "+shM[2], false); return; }
        pg.visible = shM[1].toLowerCase()==="show";
        buildSite(); showPage(0); admFb(`${shM[2]} → ${pg.visible?"visible":"hidden"} ✓`); return;
      }

      /* lock page <id> timer <date> | master */
      const lkM = raw.match(/^lock page ([\w-]+) (timer|master)(?: (.+))?$/i);
      if (lkM) {
        const pg = C.pages.find(p=>p.id===lkM[1]);
        if (!pg) { admFb("Page not found", false); return; }
        pg.lock = lkM[2].toLowerCase();
        if (pg.lock==="timer" && lkM[3]) pg.lockUntil = lkM[3].trim();
        buildSite(); showPage(0); admFb(`${lkM[1]} locked (${pg.lock}) ✓`); return;
      }

      /* unlock page */
      const ulM = raw.match(/^unlock page ([\w-]+)$/i);
      if (ulM) {
        const pg = C.pages.find(p=>p.id===ulM[1]);
        if (!pg) { admFb("Page not found", false); return; }
        pg.lock = null; pg.lockUntil = null;
        buildSite(); showPage(0); admFb(`${ulM[1]} unlocked ✓`); return;
      }

      /* set countdown <date> on <page> */
      const cdM = raw.match(/^set countdown (.+) on ([\w-]+)$/i);
      if (cdM) {
        const pg = C.pages.find(p=>p.id===cdM[2]);
        if (!pg) { admFb("Page not found", false); return; }
        pg.content.countdownTarget = cdM[1].trim();
        buildSite(); showPage(curIdx); admFb("Countdown updated ✓"); return;
      }

      /* set title/eyebrow/subtitle/body "value" on <page> */
      const txtM = raw.match(/^set (title|eyebrow|subtitle|body) "([^"]*)" on ([\w-]+)$/i);
      if (txtM) {
        const pg = C.pages.find(p=>p.id===txtM[3]);
        if (!pg) { admFb("Page not found", false); return; }
        pg.content[txtM[1].toLowerCase()] = txtM[2];
        buildSite(); showPage(curIdx); admFb(`${txtM[1]} updated ✓`); return;
      }

      /* set caption <n> "text" on <page> */
      const capM = raw.match(/^set caption (\d+) "([^"]*)" on ([\w-]+)$/i);
      if (capM) {
        const pg  = C.pages.find(p=>p.id===capM[3]);
        const idx = parseInt(capM[1])-1;
        if (!pg?.content?.photos?.[idx]) { admFb("Photo not found", false); return; }
        pg.content.photos[idx].caption = capM[2];
        buildSite(); showPage(curIdx); admFb(`Caption ${capM[1]} updated ✓`); return;
      }

      /* set folder <n> "label" on <page> */
      const flM = raw.match(/^set folder (\d+) "([^"]*)" on ([\w-]+)$/i);
      if (flM) {
        const pg  = C.pages.find(p=>p.id===flM[3]);
        const idx = parseInt(flM[1])-1;
        if (!pg?.content?.folders?.[idx]) { admFb("Folder not found", false); return; }
        pg.content.folders[idx].label = flM[2];
        buildSite(); showPage(curIdx); admFb(`Folder ${flM[1]} updated ✓`); return;
      }

      /* set question "text" on <page> */
      const qM = raw.match(/^set question "([^"]*)" on ([\w-]+)$/i);
      if (qM) {
        const pg = C.pages.find(p=>p.id===qM[2]);
        if (!pg) { admFb("Page not found", false); return; }
        pg.content.question = qM[1];
        buildSite(); showPage(curIdx); admFb("Question updated ✓"); return;
      }

      admFb("Command not recognised — see reference above ↑", false);
    } catch(err) {
      admFb("Error: "+err.message, false);
    }
  }

  /* ── export config ───────────────────────────────────── */
  function exportConfig() {
    const out  = `/* Auto-exported from Admin Panel — replace your config.js with this */\nwindow.SITE_CONFIG = ${JSON.stringify(C, null, 2)};\n`;
    const blob = new Blob([out], { type: "text/javascript" });
    const a    = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = "config.js"; a.click();
    admFb("config.js downloaded — replace your file ✓");
  }

  /* ── mobile triple-tap to reopen admin ──────────────── */
  let tapCount = 0;
  document.addEventListener("click", e => {
    if (e.clientX > window.innerWidth*0.85 && e.clientY > window.innerHeight*0.85) {
      if (++tapCount >= 3) { tapCount=0; if (window._masterUnlocked) openAdmin(); }
    } else tapCount = 0;
  });

  /* ── INIT ────────────────────────────────────────────── */
  function init() { applyTheme(T); buildSite(); }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init);
  else init();

})();
